packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@whiskeysockets/baileys'
  - bcrypt
  - prisma
  - protobufjs
  - puppeteer
  - sharp
  - tesseract.js
  - unrs-resolver
